apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: 10.34.78.249:5000/custodia-mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: CUSTODIA_SECRET_MYSQL_ROOT_PASSWORD
              # change this
              value: wordpress/db_password
          volumeMounts:
            # name must match the volume name below
            - name: mysql-persistent-storage
              # mount path within the container
              mountPath: /var/lib/mysql
            - name: custodia
              mountPath: /custodia
              readOnly: true
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: myclaim-db
        - name: custodia
          hostPath:
            path: /var/lib/custodia/client
