apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5gweb
  labels:
    name: wordpress-web
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /srv/kube-vol/wordpress/web
    server: 10.34.78.249


