apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5gdb
  labels:
    name: wordpress-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /srv/kube-vol/wordpress/db
    server: 10.34.78.249

