apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: wordpress
          image: 10.34.78.249:5000/custodia-wordpress
          ports:
          - containerPort: 80
            name: wordpress
          env:
            - name: CUSTODIA_SECRET_WORDPRESS_DB_PASSWORD
              # change this - must match mysql.yaml password
              value: wordpress/db_password
          volumeMounts:
              # name must match the volume name below
            - name: wordpress-persistent-storage
              # mount path within the container
              mountPath: /var/www/html
            - name: custodia
              mountPath: /custodia
              readOnly: true
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
           claimName: myclaim-web
        - name: custodia
          hostPath:
            path: /var/lib/custodia/client

