apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      nodePort: 30777
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: frontend
  type: NodePort

